---
title: "FIN 416 Tables"
author: "Andrew Pettifor"
format: html
editor: visual
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
library(tidyr)
library(tidyselect)
library(stats)
library(PerformanceAnalytics)
library(xts)
library(gt)
library(RTL)
library(plotly)
library(ggplot2)
library(arrow)
library(patchwork)
library(tidyquant)
library(scales)
library(ggridges)
library(viridis)
library(forcats)
library(scales)
library(lubridate)
library(stats)
library(broom)
library(gt)
library(car)
library(GGally)
library(rlang)
library(glue)
library(purrr)
library(ggfortify)
library(ggpmisc)


```

```{r echo=FALSE}

original_df <- read.csv("https://raw.githubusercontent.com/boykowealth/TailRiskPremium_PortfolioConcept/refs/heads/main/RetVolSkew_Monthly.csv")

port_df_long <- original_df %>% 
  select(DATE, PORTFOLIO, RET, IVOL, SKEW) 
  

port_df_wide <- port_df_long %>% 
  pivot_wider(names_from = PORTFOLIO, values_from = c(RET,IVOL,SKEW))

port_returns_wide <- port_df_wide %>% 
  select(DATE,RET_LongPosV1,RET_LongPosV2,RET_ShortPosV1,RET_ShortPosV2) %>% 
  mutate(RET_V1_Combined = RET_LongPosV1+RET_ShortPosV1) %>% 
  mutate(RET_V2_Combined = RET_LongPosV2 + RET_ShortPosV2)

return_columns <- grep("RET", names(port_returns_wide), value = TRUE)

port_returns_annualized <- port_returns_wide %>%
  mutate(across(all_of(return_columns), ~ (1 + .)^12 - 1))

```

# Slide 14 Performance Evaluation: New vs. Base Overall Strategy Return Summary

Need: Mean, St.Dev, Max number of Observations, T Statistic, Sharpe Ratio, Correlation

```{r echo=FALSE}

slide14_data <- port_returns_annualized %>% 
  select(DATE,RET_V1_Combined, RET_V2_Combined) %>% 
  mutate(Base = RET_V1_Combined,
         New = RET_V2_Combined,
         NewSubBase = RET_V2_Combined-RET_V1_Combined)  

slide14_table <- slide14_data %>% 
  summarise(
    across(c(Base, New, NewSubBase), list(
      Mean = ~ mean(.x, na.rm = TRUE),
      StDev = ~ sd(.x, na.rm = TRUE),
      Max = ~ max(.x, na.rm = TRUE),
      Obs = ~ sum(!is.na(.x)),
      TStat = ~ mean(.x, na.rm = TRUE) / (sd(.x, na.rm = TRUE) / sqrt(sum(!is.na(.x)))),
      Sharpe = ~ mean(.x, na.rm = TRUE) / sd(.x, na.rm = TRUE)
    )),
    Correlation = cor(Base, New, use = "complete.obs")
  )

summary_table_14 <- slide14_table %>%
  pivot_longer(everything(), names_to = c("Column", "Metric"), names_sep = "_", values_to = "Value") %>%
  pivot_wider(names_from = Column, values_from = Value)

summary_table_14 %>% gt()

```

# Slide 15 New vs. Base Overall Strategy Return Dynamics

```{r echo=FALSE}

Slide15_Data <- slide14_data %>% 
  select(DATE, Base, New) %>% 
  pivot_longer(cols = c(Base, New),
               names_to = "Portfolio",
               values_to = "Returns")


ggplot(Slide15_Data, aes(x = as.Date(DATE), y = Returns, color = Portfolio, group = Portfolio)) +
  geom_line(size = 1) + 
  labs(title = "Base vs. New Portfolio Returns Over Time",
       subtitle = "Annualized Monthly Returns",
       x = "Date",
       y = "Returns %",
       color = "Portfolio") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "1 year") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +  # Converts y-axis to percentage

  theme(legend.position = "top",
  axis.text.x = element_text(angle = 45, hjust = 1)
  )


```

# Slide 17 New vs Base Long
```{r echo=FALSE}

slide17_data <- port_returns_annualized %>% 
  select(DATE,RET_LongPosV1, RET_LongPosV2) %>% 
  mutate(BaseLong = RET_LongPosV1,
         NewLong = RET_LongPosV2,
         NewSubBaseLong = RET_LongPosV2-RET_LongPosV1)  

slide17_table <- slide17_data %>% 
  summarise(
    across(c(BaseLong, NewLong, NewSubBaseLong), list(
      Mean = ~ mean(.x, na.rm = TRUE),
      StDev = ~ sd(.x, na.rm = TRUE),
      Max = ~ max(.x, na.rm = TRUE),
      Obs = ~ sum(!is.na(.x)),
      TStat = ~ mean(.x, na.rm = TRUE) / (sd(.x, na.rm = TRUE) / sqrt(sum(!is.na(.x)))),
      Sharpe = ~ mean(.x, na.rm = TRUE) / sd(.x, na.rm = TRUE)
    )),
    Correlation = cor(BaseLong, NewLong, use = "complete.obs")
  )

summary_table_17 <- slide17_table %>%
  pivot_longer(everything(), names_to = c("Column", "Metric"), names_sep = "_", values_to = "Value") %>%
  pivot_wider(names_from = Column, values_from = Value)

summary_table_17 %>% gt()


```

# Slide 17 Visual
```{r echo=FALSE}

Slide17_Data <- slide17_data %>% 
  select(DATE, BaseLong, NewLong) %>% 
  pivot_longer(cols = c(BaseLong, NewLong),
               names_to = "Portfolio",
               values_to = "Returns")


ggplot(Slide17_Data, aes(x = as.Date(DATE), y = Returns, color = Portfolio, group = Portfolio)) +
  geom_line(size = 1) + 
  labs(title = "Base Long vs. New Long Portfolio Returns Over Time",
       subtitle = "Annualized Monthly Returns",
       x = "Date",
       y = "Returns %",
       color = "Portfolio") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "1 year") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +  

  theme(legend.position = "top",
  axis.text.x = element_text(angle = 45, hjust = 1)
  )


```

# Slide 18: New vs. Base Short Side Return Summary Statistics & Hypothesis Test

```{r echo=FALSE}
slide18_data <- port_returns_annualized %>% 
  select(DATE,RET_ShortPosV1, RET_ShortPosV2) %>% 
  mutate(BaseShort = RET_ShortPosV1,
         NewShort = RET_ShortPosV2,
         NewSubBaseShort = RET_ShortPosV2-RET_ShortPosV1)  

slide18_table <- slide18_data %>% 
  summarise(
    across(c(BaseShort, NewShort, NewSubBaseShort), list(
      Mean = ~ mean(.x, na.rm = TRUE),
      StDev = ~ sd(.x, na.rm = TRUE),
      Max = ~ max(.x, na.rm = TRUE),
      Obs = ~ sum(!is.na(.x)),
      TStat = ~ mean(.x, na.rm = TRUE) / (sd(.x, na.rm = TRUE) / sqrt(sum(!is.na(.x)))),
      Sharpe = ~ mean(.x, na.rm = TRUE) / sd(.x, na.rm = TRUE)
    )),
    Correlation = cor(BaseShort, NewShort, use = "complete.obs")
  )

summary_table_18 <- slide18_table %>%
  pivot_longer(everything(), names_to = c("Column", "Metric"), names_sep = "_", values_to = "Value") %>%
  pivot_wider(names_from = Column, values_from = Value)

summary_table_18 %>% gt()



```

# Slide 18 Visual
```{r echo=FALSE}

Slide18_Data <- slide18_data %>% 
  select(DATE, BaseShort, NewShort) %>% 
  pivot_longer(cols = c(BaseShort, NewShort),
               names_to = "Portfolio",
               values_to = "Returns")


ggplot(Slide18_Data, aes(x = as.Date(DATE), y = Returns, color = Portfolio, group = Portfolio)) +
  geom_line(size = 1) + 
  labs(title = "Base Short vs. New Short Portfolio Returns Over Time",
       subtitle = "Annualized Monthly Returns",
       x = "Date",
       y = "Returns %",
       color = "Portfolio") +
  theme_minimal() +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "1 year") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +  

  theme(legend.position = "top",
  axis.text.x = element_text(angle = 45, hjust = 1)
  )


```
# Slide 21 Table (Im Confused)
```{r echo=FALSE}
slide21_data <- port_returns_annualized %>% 
  select(DATE,RET_LongPosV1,RET_LongPosV2,RET_ShortPosV1,RET_ShortPosV2) %>% 
  mutate(
    BaseLong = RET_LongPosV1,
    BaseShort = RET_ShortPosV1,
    NewLong = RET_LongPosV2,
    NewShort = RET_ShortPosV2
             )  

slide21_table <- slide21_data %>% 
  summarise(
    across(c(BaseLong, BaseShort, NewLong, NewShort), list(
      Mean = ~ mean(.x, na.rm = TRUE),
      StDev = ~ sd(.x, na.rm = TRUE),
      Min = ~ min(.x, na.rm = TRUE),
      Max = ~ max(.x, na.rm = TRUE))))
     

summary_table_21 <- slide21_table %>%
  pivot_longer(everything(), names_to = c("Column", "Metric"), names_sep = "_", values_to = "Value") %>%
  pivot_wider(names_from = Column, values_from = Value)

summary_table_21 %>% gt()
```


